function skillsMember() {
  return [
    'HTML',
    'CSS',
    'Javascript',
    'React',
    'Node.js',
    'Express',
    'MongoDB',
    'Mongoose',
    'GraphQL',
    'Apollo',
    'REST',
    'SQL',
    'Python',
    'Django',
    'Flask',
    'Java',
    'Spring Boot',
    'C#',
    'ASP.NET',
    'Ruby',
    'Ruby on Rails',
    'PHP',
    'Laravel',
    'WordPress',
    'C++',
    'C',
    'Swift',
    'Kotlin',
    'Objective-C',
    'Go',
    'Rust',
    'Scala',
    'Haskell',
    'Elixir',
    'Clojure',
    'F#',
    'R',
    'Perl',
    'Shell',
    'Bash',
    'PowerShell',
    'TypeScript',
    'Vue.js',
    'Angular',
    'Svelte',
    'Next.js',
    'NestJS',
    'Deno',
    'Flutter',
    'React Native',
    'Ionic',
    'Cordova',
    'Xamarin',
    'Unity',
    'Unreal Engine',
    'AWS',
    'Azure',
    'Google Cloud',
    'Firebase',
    'Heroku',
    'Netlify',
    'Vercel',
    'Docker',
    'Kubernetes',
    'Jenkins',
    'Travis CI',
    'Circle CI',
    'Git',
    'GitHub',
    'GitLab',
    'Bitbucket',
    'Jira',
    'Trello',
    'Slack',
    'Discord',
    'Zoom',
    'Google Meet',
    'Microsoft Teams',
    'Figma',
    'Sketch',
    'Adobe XD',
    'Photoshop',
    'Illustrator',
    'InDesign',
    'Premiere Pro',
    'After Effects',
    'Blender',
    'Maya',
    '3ds Max',
    'ZBrush',
    'Unity',
    'Unreal Engine',
    'Tinkercad',
    'AutoCAD',
    'SolidWorks',
    'Fusion 360',
    'Raspberry Pi',
    'Arduino',
    'ESP32',
    'BeagleBone',
    'Jetson Nano',
    'Android',
    'iOS',
  };